<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="tiago-Compaq-Presario-CQ42-Notebook-PC" name="br.com.moonjava.flight.jdbc.TesteDe" tests="2" failures="0" timestamp="10 Jul 2012 01:15:49 GMT" time="1.012" errors="1">
  <testcase name="dbunit_deve_funcionar_corretamente" time="0.815" classname="br.com.moonjava.flight.jdbc.TesteDe"/>
  <testcase name="teste_banco" time="0.197" classname="br.com.moonjava.flight.jdbc.TesteDe">
    <error type="java.lang.AssertionError" message="
Expected: &lt;org.dbunit.dataset.DefaultTable[_metaData=tableName=AERONAVE, columns=[(ID, UNKNOWN, nullableUnknown), (NOME, UNKNOWN, nullableUnknown), (CODIGO, UNKNOWN, nullableUnknown), (QTD_ASSENTO, UNKNOWN, nullableUnknown), (MAPA, UNKNOWN, nullableUnknown)], keys=[], _rowList.size()=2]&gt;
     but: was &lt;org.dbunit.dataset.DefaultTable[_metaData=tableName=AERONAVE, columns=[(ID, UNKNOWN, nullableUnknown), (NOME, UNKNOWN, nullableUnknown), (CODIGO, UNKNOWN, nullableUnknown), (QTD_ASSENTO, UNKNOWN, nullableUnknown), (MAPA, UNKNOWN, nullableUnknown)], keys=[], _rowList.size()=2]&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: <org.dbunit.dataset.DefaultTable[_metaData=tableName=AERONAVE, columns=[(ID, UNKNOWN, nullableUnknown), (NOME, UNKNOWN, nullableUnknown), (CODIGO, UNKNOWN, nullableUnknown), (QTD_ASSENTO, UNKNOWN, nullableUnknown), (MAPA, UNKNOWN, nullableUnknown)], keys=[], _rowList.size()=2]>
     but: was <org.dbunit.dataset.DefaultTable[_metaData=tableName=AERONAVE, columns=[(ID, UNKNOWN, nullableUnknown), (NOME, UNKNOWN, nullableUnknown), (CODIGO, UNKNOWN, nullableUnknown), (QTD_ASSENTO, UNKNOWN, nullableUnknown), (MAPA, UNKNOWN, nullableUnknown)], keys=[], _rowList.size()=2]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at br.com.moonjava.flight.jdbc.TesteDe.teste_banco(TesteDe.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1022)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
    </error>
  </testcase> <!-- teste_banco -->
</testsuite> <!-- br.com.moonjava.flight.jdbc.TesteDe -->
